### ISSUE TITLE
local files

### ISSUE THREAD

**Issue by harmvandendorpel** [okwme/cosmos-nft#1]
Would be great if you could also publish the files on your local machine, as pointed to in `go.mod`:
```
replace github.com/cosmos/modules/incubator/nft v0.0.0-20191015123508-50d0c8092493 => /home/billy/GitHub.com/cosmos/modules/incubator/nft
```
https://github.com/okwme/cosmos-nft/blob/master/go.mod#L32

**Comment by okwme** [comment]
what do you mean by publish in this instance?
i typically work from a local version until it's stable, then publish it either via PR to the original or in a new location and update the `go.mod` by removing the replace and replacing the original with the newly published one.

is that how you mean?

**Comment by harmvandendorpel** [comment]
OK, so when I remove the `replace` line from `go.mod` I should be having the same version that you used here?

**Comment by okwme** [comment]
if you remove replace it will use the version listed in the regular section, instead of the referenced local version
